#ifndef __PVCOLLIBVERSION_H__
#define __PVCOLLIBVERSION_H__

#define _PVCOLLIB_MAJOR_	1
#define _PVCOLLIB_MINOR_	4
#define _PVCOLLIB_PATCH_	0

#define _PVCOLLIB_STRING "PVCOLLIB Release 1.4.0"

#endif // __PVCOLLIBVERSION_H__
